export const PRICES = {
  dropIn: {
    label: 'Drop-in',
    amount: 2500, // cents
    display: '€25',
    perHour: '€16.70/h',
    priceId: process.env.STRIPE_PRICE_DROP_IN!,
  },
  pack8: {
    label: '8-Class Pack',
    amount: 16900,
    display: '€169',
    perHour: '€14.08/h',
    classes: 8,
    validity: '2 months',
    priceId: process.env.STRIPE_PRICE_PACK_8!,
  },
  pack16: {
    label: '16-Class Pack',
    amount: 26900,
    display: '€269',
    perHour: '€11.21/h',
    classes: 16,
    validity: '3 months',
    priceId: process.env.STRIPE_PRICE_PACK_16!,
  },
  pack32: {
    label: '32-Class Pack',
    amount: 44900,
    display: '€449',
    perHour: '€9.35/h',
    classes: 32,
    validity: '6 months',
    priceId: process.env.STRIPE_PRICE_PACK_32!,
    bestValue: true,
  },
  sub1x: {
    label: '1× per week',
    amount: 7900,
    display: '€79',
    perHour: '€12.15/h',
    period: '/month',
    classesPerWeek: 1,
    priceId: process.env.STRIPE_PRICE_SUB_1X!,
  },
  sub2x: {
    label: '2× per week',
    amount: 12900,
    display: '€129',
    perHour: '€9.92/h',
    period: '/month',
    classesPerWeek: 2,
    priceId: process.env.STRIPE_PRICE_SUB_2X!,
  },
  sub3x: {
    label: '3× per week',
    amount: 16900,
    display: '€169',
    perHour: '€8.67/h',
    period: '/month',
    classesPerWeek: 3,
    priceId: process.env.STRIPE_PRICE_SUB_3X!,
    bestValue: true,
  },
} as const
